<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <UserSecretsId>7f3a04f9-dd70-4f7b-ba6a-56905c6c9249</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>false</Optimize>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.3.2" />
    <PackageReference Include="MySql.Data" Version="8.0.25" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\AcraData\AcraData.csproj" />
    <ProjectReference Include="..\PackUpService\CheckUpService.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="log4net.config">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
