<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <UserSecretsId>29ee2c46-dbcf-4e6f-8b52-ba760ab3a0a5</UserSecretsId>
	<ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>


  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" Version="2.2.0" />
    <ProjectReference Include="..\AcraData\AcraData.csproj" />
    <ProjectReference Include="..\AcraIDServices\AcraIDServices.csproj" />
    <ProjectReference Include="..\AcraUtils\AcraUtils.csproj" />
  </ItemGroup>

</Project>
