<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="106.6.9" />
  </ItemGroup>

	 
	

	<ItemGroup>
    <ProjectReference Include="..\AcraData\AcraData.csproj" />
    <ProjectReference Include="..\AcraUtils\AcraUtils.csproj" />
  </ItemGroup>  

</Project>
