//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Extensions.Configuration;
using System;

namespace PEK_ServiceReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions", ConfigurationName = "PEK_ServiceReference.AcraServicePortType")]
    public interface AcraServicePortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "getInfoByTin", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<PEK_ServiceReference.term1> getAcraInfoByTinAsync(PEK_ServiceReference.term request);

        [System.ServiceModel.OperationContractAttribute(Action = "getInfoBySsn", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<PEK_ServiceReference.term3> getAcraInfoBySsnAsync(PEK_ServiceReference.term2 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class RequestByTin
    {

        private string tinField;

        private string requestorCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RequestorCode
        {
            get
            {
                return this.requestorCodeField;
            }
            set
            {
                this.requestorCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class RequestBySsn
    {

        private string ssnField;

        private string requestorCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ssn
        {
            get
            {
                return this.ssnField;
            }
            set
            {
                this.ssnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RequestorCode
        {
            get
            {
                return this.requestorCodeField;
            }
            set
            {
                this.requestorCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class Response
    {

        private string errorCodeField;

        private string errorMessageField;

        private string responseDateField;

        private string refNumField;

        private string requestDateField;

        private string sSNField;

        private string tINField;

        private string taxTypeField;

        private string orgStatusField;

        private string registrationDateField;

        private string organizationTypeField;

        private string organizationNameField;

        private ResponseOrgJurLocation orgJurLocationField;

        private ResponseOrgInFactLocations[] orgInFactLocationsField;

        private ResponseOrgActivities[] orgActivitiesField;

        private ResponseTaxDebts[] taxDebtsField;

        private ResponseOrgSalaryFund[] orgSalaryFundField;

        private ResponseEmployeesNumbers[] employeesNumbersField;

        private ResponseTaxesPaid[] taxesPaidField;

        private ResponseProductsAndServicesPurchases[] productsAndServicesPurchasesField;

        private ResponseProductInStock[] productInStockField;

        private ResponseSalesTurnover[] salesTurnoverField;

        private ResponseTaxableProfit[] taxableProfitField;

        private ResponseTotalAssets[] totalAssetsField;

        private ResponseTotalLiabilities[] totalLiabilitiesField;

        private ResponseDeclLastCorrection[] declLastCorrectionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ResponseDate
        {
            get
            {
                return this.responseDateField;
            }
            set
            {
                this.responseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string RefNum
        {
            get
            {
                return this.refNumField;
            }
            set
            {
                this.refNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string RequestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string TIN
        {
            get
            {
                return this.tINField;
            }
            set
            {
                this.tINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string TaxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string OrgStatus
        {
            get
            {
                return this.orgStatusField;
            }
            set
            {
                this.orgStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string OrganizationType
        {
            get
            {
                return this.organizationTypeField;
            }
            set
            {
                this.organizationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string OrganizationName
        {
            get
            {
                return this.organizationNameField;
            }
            set
            {
                this.organizationNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public ResponseOrgJurLocation OrgJurLocation
        {
            get
            {
                return this.orgJurLocationField;
            }
            set
            {
                this.orgJurLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgInFactLocations", Order = 13)]
        public ResponseOrgInFactLocations[] OrgInFactLocations
        {
            get
            {
                return this.orgInFactLocationsField;
            }
            set
            {
                this.orgInFactLocationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgActivities", Order = 14)]
        public ResponseOrgActivities[] OrgActivities
        {
            get
            {
                return this.orgActivitiesField;
            }
            set
            {
                this.orgActivitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxDebts", Order = 15)]
        public ResponseTaxDebts[] TaxDebts
        {
            get
            {
                return this.taxDebtsField;
            }
            set
            {
                this.taxDebtsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgSalaryFund", Order = 16)]
        public ResponseOrgSalaryFund[] OrgSalaryFund
        {
            get
            {
                return this.orgSalaryFundField;
            }
            set
            {
                this.orgSalaryFundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmployeesNumbers", Order = 17)]
        public ResponseEmployeesNumbers[] EmployeesNumbers
        {
            get
            {
                return this.employeesNumbersField;
            }
            set
            {
                this.employeesNumbersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxesPaid", Order = 18)]
        public ResponseTaxesPaid[] TaxesPaid
        {
            get
            {
                return this.taxesPaidField;
            }
            set
            {
                this.taxesPaidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductsAndServicesPurchases", Order = 19)]
        public ResponseProductsAndServicesPurchases[] ProductsAndServicesPurchases
        {
            get
            {
                return this.productsAndServicesPurchasesField;
            }
            set
            {
                this.productsAndServicesPurchasesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductInStock", Order = 20)]
        public ResponseProductInStock[] ProductInStock
        {
            get
            {
                return this.productInStockField;
            }
            set
            {
                this.productInStockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesTurnover", Order = 21)]
        public ResponseSalesTurnover[] SalesTurnover
        {
            get
            {
                return this.salesTurnoverField;
            }
            set
            {
                this.salesTurnoverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxableProfit", Order = 22)]
        public ResponseTaxableProfit[] TaxableProfit
        {
            get
            {
                return this.taxableProfitField;
            }
            set
            {
                this.taxableProfitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalAssets", Order = 23)]
        public ResponseTotalAssets[] TotalAssets
        {
            get
            {
                return this.totalAssetsField;
            }
            set
            {
                this.totalAssetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalLiabilities", Order = 24)]
        public ResponseTotalLiabilities[] TotalLiabilities
        {
            get
            {
                return this.totalLiabilitiesField;
            }
            set
            {
                this.totalLiabilitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeclLastCorrection", Order = 25)]
        public ResponseDeclLastCorrection[] DeclLastCorrection
        {
            get
            {
                return this.declLastCorrectionField;
            }
            set
            {
                this.declLastCorrectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseOrgJurLocation
    {

        private string regionField;

        private string communityField;

        private string locationField;

        private string streetField;

        private string buildingField;

        private string buildingTypeField;

        private string apartmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Community
        {
            get
            {
                return this.communityField;
            }
            set
            {
                this.communityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Building
        {
            get
            {
                return this.buildingField;
            }
            set
            {
                this.buildingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string BuildingType
        {
            get
            {
                return this.buildingTypeField;
            }
            set
            {
                this.buildingTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Apartment
        {
            get
            {
                return this.apartmentField;
            }
            set
            {
                this.apartmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseOrgInFactLocations
    {

        private string regionField;

        private string communityField;

        private string locationField;

        private string streetField;

        private string buildingField;

        private string buildingTypeField;

        private string apartmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Community
        {
            get
            {
                return this.communityField;
            }
            set
            {
                this.communityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Building
        {
            get
            {
                return this.buildingField;
            }
            set
            {
                this.buildingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string BuildingType
        {
            get
            {
                return this.buildingTypeField;
            }
            set
            {
                this.buildingTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Apartment
        {
            get
            {
                return this.apartmentField;
            }
            set
            {
                this.apartmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseOrgActivities
    {

        private string orgActivityField;

        private double activityProportionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string OrgActivity
        {
            get
            {
                return this.orgActivityField;
            }
            set
            {
                this.orgActivityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public double ActivityProportion
        {
            get
            {
                return this.activityProportionField;
            }
            set
            {
                this.activityProportionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTaxDebts
    {

        private string taxDebtTypeField;

        private string taxReportPeriodField;

        private string reportUpdateDateField;

        private decimal taxDebtField;

        private decimal outstandingTaxDebtField;

        private decimal taxFinePenaltyField;

        private decimal taxOverpaymentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string TaxDebtType
        {
            get
            {
                return this.taxDebtTypeField;
            }
            set
            {
                this.taxDebtTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxReportPeriod
        {
            get
            {
                return this.taxReportPeriodField;
            }
            set
            {
                this.taxReportPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ReportUpdateDate
        {
            get
            {
                return this.reportUpdateDateField;
            }
            set
            {
                this.reportUpdateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal TaxDebt
        {
            get
            {
                return this.taxDebtField;
            }
            set
            {
                this.taxDebtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal OutstandingTaxDebt
        {
            get
            {
                return this.outstandingTaxDebtField;
            }
            set
            {
                this.outstandingTaxDebtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public decimal TaxFinePenalty
        {
            get
            {
                return this.taxFinePenaltyField;
            }
            set
            {
                this.taxFinePenaltyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public decimal TaxOverpayment
        {
            get
            {
                return this.taxOverpaymentField;
            }
            set
            {
                this.taxOverpaymentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseOrgSalaryFund
    {

        private decimal salaryFundField;

        private string taxPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal SalaryFund
        {
            get
            {
                return this.salaryFundField;
            }
            set
            {
                this.salaryFundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseEmployeesNumbers
    {

        private int employeesNumberField;

        private string taxPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int EmployeesNumber
        {
            get
            {
                return this.employeesNumberField;
            }
            set
            {
                this.employeesNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTaxesPaid
    {

        private decimal taxesPaidSumField;

        private string taxPaidTypeField;

        private string taxPeriodField;

        private string updateDateField;

        private string actOfInspectionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal TaxesPaidSum
        {
            get
            {
                return this.taxesPaidSumField;
            }
            set
            {
                this.taxesPaidSumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxPaidType
        {
            get
            {
                return this.taxPaidTypeField;
            }
            set
            {
                this.taxPaidTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ActOfInspection
        {
            get
            {
                return this.actOfInspectionField;
            }
            set
            {
                this.actOfInspectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseProductsAndServicesPurchases
    {

        private decimal productsServicesPurchaseField;

        private string taxPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal ProductsServicesPurchase
        {
            get
            {
                return this.productsServicesPurchaseField;
            }
            set
            {
                this.productsServicesPurchaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseProductInStock
    {

        private string fieldnameField;

        private decimal fieldvalueField;

        private string taxReportPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Fieldname
        {
            get
            {
                return this.fieldnameField;
            }
            set
            {
                this.fieldnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal Fieldvalue
        {
            get
            {
                return this.fieldvalueField;
            }
            set
            {
                this.fieldvalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string TaxReportPeriod
        {
            get
            {
                return this.taxReportPeriodField;
            }
            set
            {
                this.taxReportPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseSalesTurnover
    {

        private decimal salesTurnoverAmountField;

        private string salesTurnoverTypeField;

        private string taxReportPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal SalesTurnoverAmount
        {
            get
            {
                return this.salesTurnoverAmountField;
            }
            set
            {
                this.salesTurnoverAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string SalesTurnoverType
        {
            get
            {
                return this.salesTurnoverTypeField;
            }
            set
            {
                this.salesTurnoverTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string TaxReportPeriod
        {
            get
            {
                return this.taxReportPeriodField;
            }
            set
            {
                this.taxReportPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTaxableProfit
    {

        private decimal taxableProfitAmountField;

        private string taxPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal TaxableProfitAmount
        {
            get
            {
                return this.taxableProfitAmountField;
            }
            set
            {
                this.taxableProfitAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTotalAssets
    {

        private decimal fixedAssetsField;

        private decimal cashEquivalentsField;

        private decimal providedAdvancesField;

        private string taxPeriodField;

        private string updateDateField;

        private ResponseTotalAssetsAccountsReceivable[] accountsReceivableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal FixedAssets
        {
            get
            {
                return this.fixedAssetsField;
            }
            set
            {
                this.fixedAssetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal CashEquivalents
        {
            get
            {
                return this.cashEquivalentsField;
            }
            set
            {
                this.cashEquivalentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal ProvidedAdvances
        {
            get
            {
                return this.providedAdvancesField;
            }
            set
            {
                this.providedAdvancesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccountsReceivable", Order = 5)]
        public ResponseTotalAssetsAccountsReceivable[] AccountsReceivable
        {
            get
            {
                return this.accountsReceivableField;
            }
            set
            {
                this.accountsReceivableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTotalAssetsAccountsReceivable
    {

        private string fieldnameField;

        private decimal fieldvalueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Fieldname
        {
            get
            {
                return this.fieldnameField;
            }
            set
            {
                this.fieldnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal Fieldvalue
        {
            get
            {
                return this.fieldvalueField;
            }
            set
            {
                this.fieldvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTotalLiabilities
    {

        private decimal advancesReceivedField;

        private string taxPeriodField;

        private string updateDateField;

        private ResponseTotalLiabilitiesAccountsPayable[] accountsPayableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public decimal AdvancesReceived
        {
            get
            {
                return this.advancesReceivedField;
            }
            set
            {
                this.advancesReceivedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TaxPeriod
        {
            get
            {
                return this.taxPeriodField;
            }
            set
            {
                this.taxPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccountsPayable", Order = 3)]
        public ResponseTotalLiabilitiesAccountsPayable[] AccountsPayable
        {
            get
            {
                return this.accountsPayableField;
            }
            set
            {
                this.accountsPayableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseTotalLiabilitiesAccountsPayable
    {

        private string fieldnameField;

        private decimal fieldvalueField;

        private string taxReportPeriodField;

        private string updateDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Fieldname
        {
            get
            {
                return this.fieldnameField;
            }
            set
            {
                this.fieldnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal Fieldvalue
        {
            get
            {
                return this.fieldvalueField;
            }
            set
            {
                this.fieldvalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string TaxReportPeriod
        {
            get
            {
                return this.taxReportPeriodField;
            }
            set
            {
                this.taxReportPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.taxservice.am/tp3/acra/definitions")]
    public partial class ResponseDeclLastCorrection
    {

        private string declNameField;

        private string lastCorrectDateField;

        private string correctFieldField;

        private string correctFieldValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string DeclName
        {
            get
            {
                return this.declNameField;
            }
            set
            {
                this.declNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string LastCorrectDate
        {
            get
            {
                return this.lastCorrectDateField;
            }
            set
            {
                this.lastCorrectDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CorrectField
        {
            get
            {
                return this.correctFieldField;
            }
            set
            {
                this.correctFieldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string CorrectFieldValue
        {
            get
            {
                return this.correctFieldValueField;
            }
            set
            {
                this.correctFieldValueField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class term
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions", Order = 0)]
        public PEK_ServiceReference.RequestByTin RequestByTin;

        public term()
        {
        }

        public term(PEK_ServiceReference.RequestByTin RequestByTin)
        {
            this.RequestByTin = RequestByTin;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class term1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions", Order = 0)]
        public PEK_ServiceReference.Response ResponseByTin;

        public term1()
        {
        }

        public term1(PEK_ServiceReference.Response ResponseByTin)
        {
            this.ResponseByTin = ResponseByTin;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class term2
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions", Order = 0)]
        public PEK_ServiceReference.RequestBySsn RequestBySsn;

        public term2()
        {
        }

        public term2(PEK_ServiceReference.RequestBySsn RequestBySsn)
        {
            this.RequestBySsn = RequestBySsn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class term3
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.taxservice.am/tp3/acra/definitions", Order = 0)]
        public PEK_ServiceReference.Response ResponseBySsn;

        public term3()
        {
        }

        public term3(PEK_ServiceReference.Response ResponseBySsn)
        {
            this.ResponseBySsn = ResponseBySsn;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AcraServicePortTypeChannel : PEK_ServiceReference.AcraServicePortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AcraServicePortTypeClient : System.ServiceModel.ClientBase<PEK_ServiceReference.AcraServicePortType>, PEK_ServiceReference.AcraServicePortType
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public AcraServicePortTypeClient() :
                base(AcraServicePortTypeClient.GetDefaultBinding(), AcraServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AcraServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AcraServicePortTypeClient(EndpointConfiguration endpointConfiguration) :
                base(AcraServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), AcraServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AcraServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(AcraServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AcraServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(AcraServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AcraServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PEK_ServiceReference.term1> PEK_ServiceReference.AcraServicePortType.getAcraInfoByTinAsync(PEK_ServiceReference.term request)
        {
            return base.Channel.getAcraInfoByTinAsync(request);
        }

        public System.Threading.Tasks.Task<PEK_ServiceReference.term1> getAcraInfoByTinAsync(PEK_ServiceReference.RequestByTin RequestByTin)
        {
            PEK_ServiceReference.term inValue = new PEK_ServiceReference.term();
            inValue.RequestByTin = RequestByTin;
            return ((PEK_ServiceReference.AcraServicePortType)(this)).getAcraInfoByTinAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PEK_ServiceReference.term3> PEK_ServiceReference.AcraServicePortType.getAcraInfoBySsnAsync(PEK_ServiceReference.term2 request)
        {
            return base.Channel.getAcraInfoBySsnAsync(request);
        }

        public System.Threading.Tasks.Task<PEK_ServiceReference.term3> getAcraInfoBySsnAsync(PEK_ServiceReference.RequestBySsn RequestBySsn)
        {
            PEK_ServiceReference.term2 inValue = new PEK_ServiceReference.term2();
            inValue.RequestBySsn = RequestBySsn;
            return ((PEK_ServiceReference.AcraServicePortType)(this)).getAcraInfoBySsnAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AcraServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.OpenTimeout = new TimeSpan(1, 10, 0);
                result.CloseTimeout = new TimeSpan(1, 10, 0);
                result.SendTimeout = new TimeSpan(1, 10, 0);
                result.ReceiveTimeout = new TimeSpan(1, 10, 0);
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public static IConfiguration AppSetting { get; }
        static AcraServicePortTypeClient()
        {
            AppSetting = new ConfigurationBuilder()
                .SetBasePath(AppContext.BaseDirectory)
                .AddJsonFile("appsettings.json", optional: false)
                .Build();
        }
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AcraServicePort))
            {
                string connString = AcraServicePortTypeClient.AppSetting["PekConfig:HostIp"] + AcraServicePortTypeClient.AppSetting["PekConfig:Endpoint"];
                return new System.ServiceModel.EndpointAddress(connString);
                //return new System.ServiceModel.EndpointAddress("http://212.34.244.215:8080/taxsystem-ws-acra/taxpayer/acraService?wsd" +
                //        "l");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AcraServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.AcraServicePort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AcraServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.AcraServicePort);
        }

        public enum EndpointConfiguration
        {

            AcraServicePort,
        }
    }
}
