// <auto-generated />
using AcraData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace AcraData.Migrations.Trigger
{
    [DbContext(typeof(TriggerDbContext))]
    [Migration("20180302060435_InvoiceChange")]
    partial class InvoiceChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AcraData.Models.Trigger.DicTriggerReportReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ReportReasonId")
                        .HasColumnName("ReportReasonID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ReportSubReasonId")
                        .HasColumnName("ReportSubReasonID")
                        .HasColumnType("int(11)");

                    b.Property<int>("SourceId")
                        .HasColumnName("SourceId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.ToTable("DicTriggerReportReasons");
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint(20)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PersonId")
                        .HasColumnName("PersonID")
                        .HasColumnType("int(11)");

                    b.Property<int>("PersonType")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Tsid")
                        .HasColumnName("TSID")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasName("IX_Status");

                    b.HasIndex("Tsid")
                        .HasName("fk_TSID");

                    b.ToTable("TriggerPersons");
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerPersonsDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint(20)");

                    b.Property<int>("PersonId")
                        .HasColumnName("PersonID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("Tpid")
                        .HasColumnName("TPID")
                        .HasColumnType("bigint(20)");

                    b.HasKey("Id");

                    b.HasIndex("Tpid")
                        .HasName("fk_TPID");

                    b.ToTable("TriggerPersonsDetails");
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint(20)");

                    b.Property<DateTime>("ActivityTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PersonId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int(11)");

                    b.Property<string>("ReportInfo")
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("SubReasonId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Tsid")
                        .HasColumnName("TSID")
                        .HasColumnType("int(11)");

                    b.Property<long?>("UserActivityId")
                        .HasColumnType("bigint(20)");

                    b.HasKey("Id");

                    b.HasIndex("Tsid")
                        .HasName("fk_RepTSID");

                    b.ToTable("TriggerReports");
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnName("SourceID")
                        .HasColumnType("int(11)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.ToTable("TriggerSources");
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerVolume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Tsid")
                        .HasColumnName("TSID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Volume")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("Tsid")
                        .HasName("fk_SourceVolume");

                    b.HasIndex("Date", "Tsid")
                        .IsUnique()
                        .HasName("pk_Date");

                    b.ToTable("TriggerVolumes");
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerPerson", b =>
                {
                    b.HasOne("AcraData.Models.Trigger.TriggerSource", "TriggerSource")
                        .WithMany("TriggerPersons")
                        .HasForeignKey("Tsid")
                        .HasConstraintName("fk_TSID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerPersonsDetail", b =>
                {
                    b.HasOne("AcraData.Models.Trigger.TriggerPerson", "TriggerPerson")
                        .WithMany("TriggerPersonsDetails")
                        .HasForeignKey("Tpid")
                        .HasConstraintName("fk_TPID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerReport", b =>
                {
                    b.HasOne("AcraData.Models.Trigger.TriggerSource", "TriggerSource")
                        .WithMany("TriggerReports")
                        .HasForeignKey("Tsid")
                        .HasConstraintName("fk_RepTSID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AcraData.Models.Trigger.TriggerVolume", b =>
                {
                    b.HasOne("AcraData.Models.Trigger.TriggerSource", "Ts")
                        .WithMany("TriggerVolumes")
                        .HasForeignKey("Tsid")
                        .HasConstraintName("fk_SourceVolume");
                });
#pragma warning restore 612, 618
        }
    }
}
